#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="thanhtoanonline")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTHONGTINKH(THONGTINKH instance);
    partial void UpdateTHONGTINKH(THONGTINKH instance);
    partial void DeleteTHONGTINKH(THONGTINKH instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["thanhtoanonlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<THONGTINKH> THONGTINKHs
		{
			get
			{
				return this.GetTable<THONGTINKH>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_laySoTaiKhoan")]
		public ISingleResult<sp_laySoTaiKhoanResult> sp_laySoTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sotk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> socsc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sotk, socsc);
			return ((ISingleResult<sp_laySoTaiKhoanResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINKH")]
	public partial class THONGTINKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STK;
		
		private int _CSC;
		
		private int _SODU;
		
		private string _TEN;
		
		private string _HO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTKChanging(int value);
    partial void OnSTKChanged();
    partial void OnCSCChanging(int value);
    partial void OnCSCChanged();
    partial void OnSODUChanging(int value);
    partial void OnSODUChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    #endregion
		
		public THONGTINKH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STK
		{
			get
			{
				return this._STK;
			}
			set
			{
				if ((this._STK != value))
				{
					this.OnSTKChanging(value);
					this.SendPropertyChanging();
					this._STK = value;
					this.SendPropertyChanged("STK");
					this.OnSTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSC", DbType="Int NOT NULL")]
		public int CSC
		{
			get
			{
				return this._CSC;
			}
			set
			{
				if ((this._CSC != value))
				{
					this.OnCSCChanging(value);
					this.SendPropertyChanging();
					this._CSC = value;
					this.SendPropertyChanged("CSC");
					this.OnCSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODU", DbType="Int NOT NULL")]
		public int SODU
		{
			get
			{
				return this._SODU;
			}
			set
			{
				if ((this._SODU != value))
				{
					this.OnSODUChanging(value);
					this.SendPropertyChanging();
					this._SODU = value;
					this.SendPropertyChanged("SODU");
					this.OnSODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_laySoTaiKhoanResult
	{
		
		private int _SODU;
		
		public sp_laySoTaiKhoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODU", DbType="Int NOT NULL")]
		public int SODU
		{
			get
			{
				return this._SODU;
			}
			set
			{
				if ((this._SODU != value))
				{
					this._SODU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
